VIRTUAL_WIDTH = 450
VIRTUAL_HEIGHT = 250

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

TILE_SIZE = 16

--
-- entity constants
--
PLAYER_WALK_SPEED = 60
AGRO_RANGE = 10 * TILE_SIZE
AGRO_WALK_SPEED = 70
AGRO_START_GRACE = 1

--
-- projective constants
--
SCROLL_PROJECTILES = 6
SCROLL_ANGLE_INC = (2 * math.pi) / SCROLL_PROJECTILES
PROJECTILE_SPEED = 150
PROJECTILE_TRAVEL_DIST = 10
SHOT_COOLDOWN = 0.5

--
-- potion constants
--
POT_DMG_INCREASE = 0.1
POT_SPD_INCREASE = 4

--
-- map constants
--
MAP_WIDTH = 60
MAP_HEIGHT = 60
NUM_ENTITIES = 0
WIN_CONDITION = 25
CHEST_FREQUENCY = 1 -- integer, higher is lower spawn chance

MAP_RENDER_OFFSET_X = (VIRTUAL_WIDTH - (MAP_WIDTH * TILE_SIZE)) / 2
MAP_RENDER_OFFSET_Y = (VIRTUAL_HEIGHT - (MAP_HEIGHT * TILE_SIZE)) / 2
NUMBER_OF_OBSTACLES = MAP_HEIGHT * MAP_WIDTH / 40
--
-- tile IDs
--
TILE_TOP_LEFT_CORNER = 9
TILE_TOP_RIGHT_CORNER = 11
TILE_BOTTOM_LEFT_CORNER = 13
TILE_BOTTOM_RIGHT_CORNER = 15

TILE_EMPTY = 18

TILE_FLOORS = {
    1, 2, 3
}

TILE_TOP_WALLS = {10}
TILE_BOTTOM_WALLS = {14}
TILE_LEFT_WALLS = {12}
TILE_RIGHT_WALLS = {16}